### ISSUE TITLE
gridmanager.js

### ISSUE THREAD

**Issue by neokoenig** [twbs/bootstrap-expo#1017]
A way of building rows and grids with built in editable regions; requires jQuery, jQueryUI, Bootstrap 3.x, & optional TinyMCE or CKEditor

Repo:
https://github.com/neokoenig/jQuery-gridmanager

Demo:
http://neokoenig.github.io/jQuery-gridmanager/demo/

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
