### ISSUE TITLE
http://snipplicious.com/

### ISSUE THREAD

**Issue by werewolfrex** [twbs/bootstrap-expo#1066]
Hello this is site about bootstrap which is built on latest bootstrap :-)

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
