### ISSUE TITLE
Bootstrap Checkbox X

### ISSUE THREAD

**Issue by kartik-v** [twbs/bootstrap-expo#1071]
An [extended checkbox jQuery plugin](http://plugins.krajee.com/checkbox-x) for Bootstrap 3, which allows three checkbox states, Bootstrap 3 form control styles & glyphs, keyboard manipulation, and more. View a [complete usage and demo](http://plugins.krajee.com/checkbox-x/demo).

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
