### ISSUE TITLE
Bootstrap Carnival 

### ISSUE THREAD

**Issue by bharani91** [twbs/bootstrap-expo#1086]
Hi,

I was hoping if you could add my side project Bootstrap Carnival (http://bootstrapcarnival.com) to your resources list.

Thanks,
Bharani

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
