### ISSUE TITLE
BS Class Maker - Customizer http://www.bsclassmaker.com

### ISSUE THREAD

**Issue by markusfantone** [twbs/bootstrap-expo#1117]
Hi,

I'm here to introduce the BS Class Maker project.
It's a Bootstrap customizer!
It's simple, you'll build your own classes by selecting a name, the main color, the text color and the components you want to generate and we'll do the rest.
The hover properties and color variations is on us.
The differential is that we don't override your CSS like the other known tools, we create a new one, like an extension. 
With that it become possible to use products like Nuget to have the latest version of the framework.
As an example, we create 4 color sets to download based on some social networks, one for Facebook, one for Twitter, one for Google+ and one for LinkedIn.

We hope you enjoy the tool! =)
If you don't like it, we would really appreciate a feedback from you.
http://www.bsclassmaker.com

Congratulations on the framework, it's simply awesome!

Best Regards,

Markus Fantone
BS Class Maker Team
+5511974198301

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
