### ISSUE TITLE
New Plugin: Bootstrap Tabs X

### ISSUE THREAD

**Issue by kartik-v** [twbs/bootstrap-expo#1141]
An [extended Bootstrap Tabs plugin](http://plugins.krajee.com/tabs-x) for Bootstrap 3, with ability to position/align tabs in multiple ways, add borders, maintain rotated/sideway headers, and more. This plugin includes various CSS3 styling enhancements and various tweaks to the core Bootstrap 3 Tabs plugin. View a [complete usage and demo](http://plugins.krajee.com/tabs-x/demo).

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
