### ISSUE TITLE
general PHP helper for Twitter Bootstrap

### ISSUE THREAD

**Issue by mtancoigne** [twbs/bootstrap-expo#1142]
I started this PHP helper to create twitter bootstrap elements, feel free to add it if you think it's an interesting project.

This helper is meant to be used in PHP apps, templates,... and can be easily adapted to an existing framework.

[Github](https://github.com/el-cms/Tbs)
[Demo (currently available elements)](http://experimentslabs.com/test/tbs/)

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
