### ISSUE TITLE
bforms.veritech.io

### ISSUE THREAD

**Issue by mariuscosareanu** [twbs/bootstrap-expo#1182]
The BForms open source framework consists of a collection of ASP.NET MVC HTML Helpers, Javascript AMD modules, custom CSS made with SASS that extends Twitter Bootstrap v3 and makes development of rich user interfaces easy.

[ ![BForms](https://cloud.githubusercontent.com/assets/2662778/4151247/4f5e6a70-3444-11e4-8894-8fc452678929.jpg) ](http://bforms.veritech.io)

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
