### ISSUE TITLE
Bootstrap Helpers for Ruby

### ISSUE THREAD

**Issue by hnrch02** [twbs/bootstrap-expo#1189]
https://github.com/Fullscreen/bh

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
