### ISSUE TITLE
Please add GrayGrids on resource list

### ISSUE THREAD

**Issue by Musharofchy** [twbs/bootstrap-expo#1457]
Hi,
GrayGrids Provides Free Downloadable Bootstrap Templates and resources. Everything is Free/non-profit and ad free. If you add http://graygrids.com on resource list, it will be helpful for everyone to get premium quality free Bootstrap templates easily.

Thanks

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
