### ISSUE TITLE
Capture

### ISSUE THREAD

**Issue by pixelhint** [twbs/bootstrap-expo#1542]
![index](https://cloud.githubusercontent.com/assets/11059472/6247152/f1a42be2-b768-11e4-843a-a7156a4d3638.jpg)

Capture is a single page app landing page, built with bootstrap v3.3.2 with the help of other javascript libraries, the layout is responsive, clean and beautiful.

You view the live version here http://pixelhint.com/demo/capture

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
