### ISSUE TITLE
Site Submission: Aurum - Minimalist Bootstrap Shop

### ISSUE THREAD

**Issue by LaboratorThemes** [twbs/bootstrap-expo#1568]
Hi there,

we would like to submit our site/theme that is build with Bootstrap 3.0 - Aurum: http://themes.laborator.co/aurum/fashion/

Best Regards
Laborator Team

**Comment by pcgtech** [comment]
https://www.tribalevent.com/

https://www.tribalevent.com/social/

**Comment by mdo** [comment]
Wait, is this an actual site or is it a theme?

**Comment by LaboratorThemes** [comment]
Hi there,

it's a theme :).

Art

On Mon, Mar 9, 2015 at 12:41 PM, Mark Otto <notifications@github.com> wrote:

> Wait, is this an actual site or is it a theme?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap-expo/issues/1568#issuecomment-77839036>
> .
>



-- 

[image: envato_logo] Follow us on Envato
<http://themeforest.net/user/Laborator/follow>
[image: envato_logo] Like us on Facebook
<https://www.facebook.com/laboratorcreative>
[image: envato_logo] Follow on Twitter <https://twitter.com/thelaborator>

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
