### ISSUE TITLE
5 bootstrap freebies from Creativ-Tim

### ISSUE THREAD

**Issue by itflow** [twbs/bootstrap-expo#1625]
Dear, 

I am writing to you in order to share link to article which describes 5 nice free tools (freebies) from Creativ-Tim:
- Register/Login modal
- Rotating CSS Cards
- Datapicker
- Bootstrap wizard
- Feedback Form 

Post addres:
http://blog.creative-tim.com/web-design/5-outstanding-useful-tools-website/

Could you share it with others? Perhaps post on your webpage/newsletter ? 

Kind regards,
Dawid

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
