### ISSUE TITLE
Framer - Multi-Purpose Bootstrap Template

### ISSUE THREAD

**Issue by awerest** [twbs/bootstrap-expo#1643]
Awesome components based framework

We created digital product that will help brands thrive in a connected world. Meet Framer, extended and designed framework based on Bootstrap with easy-to-use attribute that will speed up process of building a website and give awesome end product.

One template infinite possibilities

Framer is not just one template, it’s a tons of components that together create unlimited number of templates.

Demo: http://www.awerest.com/demo/framer/
Download: http://themeforest.net/item/framer-multipurpose-bootstrap-html5-template/10898825?ref=awerest

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site is still using Bootstrap and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
