### ISSUE TITLE
Site Submission: Quire

### ISSUE THREAD

**Issue by jesschen-potix** [twbs/bootstrap-expo#1715]
Quire is a task management tool, and we(Potix) have just renew our website recently. https://quire.io/

**Comment by mdo** [comment]
Looking good! Only have one small nit to report—there's a small bug on the homepage with the border-radius of your green button and the input field.

**Comment by jesschen-potix** [comment]
@mdo Thanks for taking the time to have a good, really appreciated!
May I ask more specifically of where the bug is? I've checked through the code and couldn't find or see the error you've pointed out.
Thanks again!

**Comment by mdo** [comment]
Note the border radius here on the input and the button here:

<img width="641" alt="screen shot 2015-09-28 at 11 28 09 am" src="https://cloud.githubusercontent.com/assets/98681/10144741/0b803fe6-65d4-11e5-963e-3bb91dbe49ce.png">

**Comment by jesschen-potix** [comment]
@mdo Thanks for the note! We've finally fixed it, and hope you could have a look.
Have a great day.

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
