### ISSUE TITLE
Resource suggestion

### ISSUE THREAD

**Issue by alfredobarron** [twbs/bootstrap-expo#1717]
hi,
Smoke is a Jquery Plugin validate forms, notifications, progressbar and more for bootstrap
url : http://alfredobarron.github.io/smoke/
thx

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
