### ISSUE TITLE
Sumission to Expo

### ISSUE THREAD

**Issue by pozh** [twbs/bootstrap-expo#1722]
hi!
I'd love to add templates from my http://gettemplate.com to the Expo. http://www.gettemplate.com/demo/magister/ and http://www.gettemplate.com/demo/progressus/ seem to be the best ones in my collection. What do you think?

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
