### ISSUE TITLE
DribbbleFolio

### ISSUE THREAD

**Issue by gsvineeth** [twbs/bootstrap-expo#1729]
gsvineeth.com/freebies/dribbble-portfolio

**Comment by mdo** [comment]
If this has a project page, we could link to that.

**Comment by gsvineeth** [comment]
Hi @mdo  

I have published this as a dribbble shot.
Please find the link here :  https://dribbble.com/shots/2035170-DribbbleFolio-Dribbble-Portfolio-HTML-Template-Free-Download 

Between thanks a ton for all your contributions! 

Regards,
Vineeth Gopal

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
