### ISSUE TITLE
Bootstrap freebies and tools - resource

### ISSUE THREAD

**Issue by alexandru-paduraru** [twbs/bootstrap-expo#1734]
http://www.creative-tim.com/

**Comment by alexandru-paduraru** [comment]
Hi Mark,

Will be our website added to the resources page of Bootstrap? Or how can the other Bootstrap user benefit from our resource?

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
