### ISSUE TITLE
New website suggestion

### ISSUE THREAD

**Issue by teamrevox** [twbs/bootstrap-expo#1766]
Hi there

We would like to show case what we build with using bootstrap.

A premium admin dashboard
http://pages.revox.io/dashboard/latest/html/

And a front-end website/s (They are showcased in each thumbnail on the link below)

http://pages.revox.io/

Thank you bootstrap! :)

**Comment by josephbona** [comment]
Very impressive.
Nice work @teamrevox

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
