### ISSUE TITLE
Submit my bootstrap website

### ISSUE THREAD

**Issue by plcossette** [twbs/bootstrap-expo#1974]
Hi, 

Last year, you publish one of my website (http://resto-elephant.com/) and I want to suggest another website that I just did. 

Café Frida 
http://cafefrida.ca/

Thank you and have a nice day!

Pier-Luc Cossette
plcossette.com

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
