### ISSUE TITLE
Suggest a Site: http://realmadridlegends.com/

### ISSUE THREAD

**Issue by ncgordan** [twbs/bootstrap-expo#1980]
I don't know if my site is high quality, beautiful, and a comprehensive example of building with Bootstrap, but I have to try, and it's up to you accepting the submission. Thank you very much (from Spain).
http://realmadridlegends.com/

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
