### ISSUE TITLE
Bootstrap Expo Submission

### ISSUE THREAD

**Issue by GuillaumeSerrat** [twbs/bootstrap-expo#2007]
https://funio.com/

**Comment by GuillaumeSerrat** [comment]
![canadian website hosting services cheap small business web hosting in canada from funio](https://cloud.githubusercontent.com/assets/1109150/11701047/5804e3c6-9e9b-11e5-8755-771ad8b6093e.png)

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
