### ISSUE TITLE
Site Suggestion - Anjos Ramos

### ISSUE THREAD

**Issue by gabrielhsp** [twbs/bootstrap-expo#2052]
Hi, i'm a brazilian front-end developer. In my company we used Bootstrap to develop a website to a law client. Here's the project we built:

[anjosramos.com.br](http://anjosramos.com.br)

I hope that we can enter on Bootstrap Expo!

Thanks :D

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
