### ISSUE TITLE
jayarajpr.com site submission

### ISSUE THREAD

**Issue by jayarajpr** [twbs/bootstrap-expo#2064]
Hi,

Jayarajpr.com (www.jayarajpr.com) is my personal website made with bootstrap 3.3.6.
Is it possible could you please put it in  Bootstrap  expo gallery

Thanks!
Jayaraj  PR

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
