### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by aicragellebasi** [twbs/bootstrap-expo#2086]
Hi there,
I am so excited by bootstrap 4. I a using it in a very modest and simple website: http://thecplab.io/
Not sure if this is sophisticated enough to pretend being exposed in Bootstrap Expo, but does not hurt trying.
Thanks. Love Bootstrap.

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
