### ISSUE TITLE
Staatliche Mussen zu Berlin

### ISSUE THREAD

**Issue by xmental** [twbs/bootstrap-expo#2120]
Brand new relaunch with bootstrap 4, maybe the first one? Check out: [ Website Staatliche Museen zu Berlin](http://www.smb.museum/)
Hope you like it. Made by xmental 
<img width="1499" alt="smb" src="https://cloud.githubusercontent.com/assets/6349184/15212061/0970b3ac-183f-11e6-85af-4af88407dbdb.png">

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
