### ISSUE TITLE
Beautiful website build with Bootstrap

### ISSUE THREAD

**Issue by davidbanu** [twbs/bootstrap-expo#2121]
[David Banu website](http://www.davidbanu.com)

**Comment by radek024** [comment]
I dont sure but i guess that the page is based on start bootstrap template, they're very similar.

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
