### ISSUE TITLE
KOKOWINKA created using Bootstrap 3

### ISSUE THREAD

**Issue by lujuhu** [twbs/bootstrap-expo#2155]
Hi,

I would like to share my web-app created in Bootstrap 3 with you to include it, if you think is a good example, in the bootstrap expo.

The web-app is a kind of fashion online store focused on the spanish market.

[http://kokowinka.com](http://kokowinka.com)

Kind regards,
Luis.

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
