### ISSUE TITLE
Bootstrap Expo: MakeAndSet.com

### ISSUE THREAD

**Issue by makeandset** [twbs/bootstrap-expo#2162]
Hey Bootstrap expo, 
Launched https://makeandset.com 
It's a bootstrap built free premium templates resource, we love to be featured. 
Thank you. 

![make and set](https://cloud.githubusercontent.com/assets/20138324/17392411/dddab704-5a3a-11e6-8c62-9a886046391b.png)

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
