### ISSUE TITLE
Site suggestion: presentation.mdbootstrap.com

### ISSUE THREAD

**Issue by mattonit** [twbs/bootstrap-expo#2184]
Hello,

We’ve managed to combine best design pattern of Material Design with Bootstrap best features and created Material Design for Bootstrap.

Now we want Bootstrap enthusiasts to get to know our team and mission and we would love to be mentioned on your exposition. That’s why we’ve created a presentation page of what’s best in our framework and in our family: [http://presentation.mdbootstrap.com/](http://presentation.mdbootstrap.com/)

Best regards,
Bartlomiej Malanowski

**Comment by mattonit** [comment]
@mdo, any progress?

**Comment by mattonit** [comment]
@mdo any updates on this?

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
