### ISSUE TITLE
Multi-Demo Bootstrap Admin Theme

### ISSUE THREAD

**Issue by sean0205** [twbs/bootstrap-expo#2311]
Hello,

First of all, let us thank you for making such perfect web framework that changed the web a lot recent years. Nowadays frontend development can not be imagined without Bootstrap. You are the living heroes! 

In case if that can be possible,  could you please consider listing our Metronic theme ?

http://keenthemes.com/metronic

And also our custom made datatable plugin:

http://keenthemes.com/metronic/preview/default/html/components/datatables/base/column-rendering.html
http://keenthemes.com/metronic/preview/default/html/components/datatables/locked/right.html

Thanks in advance.

**Comment by dhg** [comment]
Thanks so much for submitting to the Expo and we apologize for the belated reply. The good news is, we're starting to add new sites and resources to the Expo again.

As a first step, we're closing all submissions older than a year since many are no longer relevant, but if your site or resource is still applicable and you want to be considered, we encourage you to resubmit by creating a new issue with your information!

Thanks for your understanding. 

Bootstrap Team :)
